Upgraded to Dojo 0.6.0 + sozo profiles

diff --git a/dojo/migrate b/dojo/migrate
--- a/dojo/migrate
+++ b/dojo/migrate
@@ -1,30 +1,70 @@
 #!/bin/bash
 set -e
 
+if [ $# -ge 1 ]; then
+    export PROFILE=$1
+else
+    export PROFILE="dev"
+fi
+
 #-----------------
 # env setup
 #
+export MANIFEST_FILE_PATH="./manifests/$PROFILE/manifest.json"
+export BINDINGS_PATH="./bindings/typescript"
+export CLIENT_PATH="../client/src/generated"
+export CLIENT_MANIFEST_PATH="../client/src/generated/$PROFILE"
 export WORLD_ADDRESS=$(toml get Scarb.toml --raw tool.dojo.env.world_address)
-export RPC_URL=$(toml get Scarb.toml --raw tool.dojo.env.rpc_url)
+export RPC_URL=$(toml get Scarb.toml --raw profile.$PROFILE.tool.dojo.env.rpc_url)
+
+if [[
+  -z "$PROFILE" ||
+  -z "$MANIFEST_FILE_PATH" ||
+  "$WORLD_ADDRESS" != "0x"* ||
+  "$RPC_URL" != "http"*
+]]; then
+  echo "! Missing data 👎"
+  exit 1
+fi
 
 #-----------------
 # migrate
 #
 echo "------------------------------------------------------------------------------"
 echo "Migrating..."
-sozo migrate --world $WORLD_ADDRESS
+echo ""
+echo "PROFILE: $PROFILE"
+# sozo --profile $PROFILE migrate plan --world $WORLD_ADDRESS
+# exit 0
+sozo -P $PROFILE migrate apply --world $WORLD_ADDRESS
 
 #-----------------
 # auth write
 #
-scripts/default_auth.sh
+scripts/default_auth.sh $PROFILE
+
 
 #-----------------
-# client update
+# copy files
 #
-cp target/dev/manifest.json ../client/src/
-cd ../client
-npm run create-components $RPC_URL $WORLD_ADDRESS
+if [[ "$PROFILE" == "dev" ]]; then
+  # copy manifest to client
+  mkdir -p $CLIENT_MANIFEST_PATH
+  cp $MANIFEST_FILE_PATH $CLIENT_MANIFEST_PATH/
+
+  # TODO: Enable this when bindings are working
+  # generate and cop bindings
+  # sozo build --typescript
+  # cp $BINDINGS_PATH/* $CLIENT_PATH/
+
+  # TODO: Remove this when bindings are working
+  # copy to client
+  cd ../client
+  npm run create-components $RPC_URL $WORLD_ADDRESS
+
+  # list copied files
+  ls -ld $CLIENT_PATH/* $CLIENT_MANIFEST_PATH/* | grep -E 'ts|json'
+fi
 
 #-----------------
 echo "--- DONE! 👍"
diff --git a/dojo/run_torii b/dojo/run_torii
--- a/dojo/run_torii
+++ b/dojo/run_torii
@@ -4,4 +4,11 @@ set -e
 export WORLD_ADDRESS=$(toml get Scarb.toml --raw tool.dojo.env.world_address)
 echo "@WORLD: $WORLD_ADDRESS"
 
-torii -w $WORLD_ADDRESS $*
+if [[
+  "$WORLD_ADDRESS" != "0x"*
+]]; then
+  echo "! Missing data 👎"
+  exit 1
+fi
+
+torii --world $WORLD_ADDRESS $*
